### ISSUE TITLE
[WIP] Add default overrides for rpc-maas in Kilo / Liberty / Mitaka 

### ISSUE THREAD

**Issue by npawelek** [rcbops/rpc-maas#275]
Based on the current installation mechanisms, there's a need to add defaults on a per-release basis. This is mainly to reduce monitoring noise on alarms that support is unable to directly influence. Disabling an alarm still runs the associated check to gather metrics, but it will not generate any notifications.

#### Kilo

```yaml
# Set overrides for check periods
maas_check_period_override:
  disk_utilisation: 900
# Disable the following MaaS alarms
# Issue: https://github.com/rcbops/u-suk-dev/issues/1081
maas_excluded_alarms:
  - '^idle_percent_average.*'
  - '^memory_check.*'
  - '^Network receive rate.*'
  - '^Network transmit rate.*'
  - '^percentage_disk_utilisation.*'
# swift-recon does not have '--time' option in Kilo
maas_excluded_checks:
  - 'swift_time_sync_check'
# Ansible 1.9 compatibility
ansible_host: "{{ ansible_ssh_host }}"
```

#### Liberty

```yaml
# Set overrides for check periods
maas_check_period_override:
  disk_utilisation: 900
# Disable the following MaaS alarms
# Issue: https://github.com/rcbops/u-suk-dev/issues/1081
maas_excluded_alarms:
  - '^idle_percent_average.*'
  - '^memory_check.*'
  - '^Network receive rate.*'
  - '^Network transmit rate.*'
  - '^percentage_disk_utilisation.*'
maas_excluded_checks:
  - 'filebeat_process_check'
# Ansible 1.9 compatibility
ansible_host: "{{ ansible_ssh_host }}"
```

#### Mitaka

```yaml
# Set overrides for check periods
maas_check_period_override:
  disk_utilisation: 900
# Disable the following MaaS alarms
# Issue: https://github.com/rcbops/u-suk-dev/issues/1081
maas_excluded_alarms:
  - '^idle_percent_average.*'
  - '^memory_check.*'
  - '^Network receive rate.*'
  - '^Network transmit rate.*'
  - '^percentage_disk_utilisation.*'
maas_excluded_checks: []
# Ansible 1.9 compatibility
ansible_host: "{{ ansible_ssh_host }}"
```
